<a href="https://colab.research.google.com/github/davidbza/Python_1_talleres/blob/main/Taller_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="120px" src="https://www.udea.edu.co/wps/wcm/connect/udea/df55724e-3ebc-46c6-b608-fb9206b3fede/facultad-economicas.png?MOD=AJPERES&CVID=nc5zPyj" align="Center" hspace="10px" vspace="10px"></p>


#***Python I - Introducción a modelos económicos y financieros con Python***

---


#**Sesión 3**
# Docente: *Cristian Ruiz Parra*

---
Contenido de la sesión
- Introducción a Numpy
- Operaciones con arreglos matriciales
- principales funciones
- Taller practico

# **Numpy (np)**

NumPy (Numerical Python) es la biblioteca fundamental para computación científica en Python. Proporciona un objeto de arreglo de datos multidimensional de alto rendimiento y herramientas para trabajar con estos "arrays o arreglos".

Primer paso para acceder a Numpy es importarlo

In [6]:
import numpy as np

Recuerda llamarlo con el alias (np) para simplificar el llamar las funciones propias de Numpy

In [7]:
import numpy as np

# 📦 CREACIÓN DE ARRAYS NUMPY
def demostracion_arrays():
    # Desde lista Python
    lista_python = [1, 2, 3, 4, 5]
    array_numpy = np.array(lista_python)

    print("🎯 COMPARACIÓN LISTA vs ARRAY:")
    print(f"Lista Python: {lista_python} (tipo: {type(lista_python)})")
    print(f"Array NumPy:  {array_numpy} (tipo: {type(array_numpy)})")
    print(f"Tipo datos array: {array_numpy.dtype}")
    print(f"Forma del array: {array_numpy.shape}")
    print(f"Dimensiones: {array_numpy.ndim}D")

# Ejecutar demostración
demostracion_arrays()

🎯 COMPARACIÓN LISTA vs ARRAY:
Lista Python: [1, 2, 3, 4, 5] (tipo: <class 'list'>)
Array NumPy:  [1 2 3 4 5] (tipo: <class 'numpy.ndarray'>)
Tipo datos array: int64
Forma del array: (5,)
Dimensiones: 1D


# ¿Por que usar Numpy en lugar de las listas de Python?

La respuesta a esta pregunta es por eficiencia computacional, los algoritmos de Numpy estan implementados en "C" y se encuentran optimizados

In [8]:
import time

def comparacion_velocidad():
    # Datos de ejemplo
    datos = list(range(1000000))
    array_numpy = np.array(datos)

    # Operación con lista Python
    inicio_lista = time.time()
    resultado_lista = [x * 2 for x in datos]
    tiempo_lista = time.time() - inicio_lista

    # Operación con NumPy
    inicio_numpy = time.time()
    resultado_numpy = array_numpy * 2
    tiempo_numpy = time.time() - inicio_numpy

    print("⚡ COMPARACIÓN DE VELOCIDAD:")
    print(f"Lista Python: {tiempo_lista:.6f} segundos")
    print(f"NumPy: {tiempo_numpy:.6f} segundos")
    print(f"NumPy es {tiempo_lista/tiempo_numpy:.1f}x más rápido")
    print(datos[0:10])
    print(array_numpy[0:10])
    print(resultado_lista[0:10])
    print(resultado_numpy[0:10])

comparacion_velocidad()

⚡ COMPARACIÓN DE VELOCIDAD:
Lista Python: 0.054818 segundos
NumPy: 0.004852 segundos
NumPy es 11.3x más rápido
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]


# **Arreglos de datos**

Existen multiples formas de organizar la información en función de la cantidad de dimensiones de los datos, que podria verse también si existe mayor interacción entre diferentes cantidades de variables y estructuras temporales

¿Cómo conocemos estos arreglos en función de sus dimensiones?

0D: Escalar

1D: Vectores

2D: Matrices

3D: Tensores

4D: Hipercubos

## 1D array (vector)

un arreglo unidimensional es una colecion de tipos de datos los cuales se encuntran indexados ( tal y como las listas ). A diferencia de las listas, los arreglos 1D ( y en general los arreglos de cualquier dimension ) solo pueden contener un tipo de dato.

Los arreglos de python soportan indexacion y slicing

para crear un arreglo 1D de python , podemos usar una lista de numpy


In [9]:
v = np.array([1,2,2,5,2.6,5,6,7,3]) #creacion de un arreglo 1D de numpy
print(type(v))
v #Veamos el vector y a que clase pertenece (esto es , veamos que tipo de dato es)

<class 'numpy.ndarray'>


array([1. , 2. , 2. , 5. , 2.6, 5. , 6. , 7. , 3. ])

In [10]:
#indexacion
v[0], v[1] , v[-1] , v[4]

(np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(2.6))

**Formato para llamar subarreglos (Slicing)**

Para llamar una parte de un Arreglo en 1D tenemos el fotmato siguiente:

Nombre del arreglo[Elmento inicial:Elemento final:paso]



In [11]:
#slicing [indice_inicial:indice_fianl:paso]
v[0:7:2], v[::-1] , v[1::3] , v[5::]

(array([1. , 2. , 2.6, 6. ]),
 array([3. , 7. , 6. , 5. , 2.6, 5. , 2. , 2. , 1. ]),
 array([2. , 2.6, 7. ]),
 array([5., 6., 7., 3.]))

**Lista de elementos**

Nombre del arreglo[[Elemento1, elmento2, elemento3,... elementon]]

In [12]:
# otras formas de hacer indexing (usar una lista para hacer indexing)
v[[1,3,5,6]]

array([2., 5., 5., 6.])

**Formato Buleano**
Aquí describiremos que posiciones queremos que conformen nuestro nuevo arreglo

Nombre del arreglo[[(True or false, True or false, True or false, True or false... True or false]]

In [13]:
#Indexacion usando tipos buleanos
v[[True , True , False, False, True, True, False, False, False]]

array([1. , 2. , 2.6, 5. ])

In [14]:
#Indexacion usando tipos buleanos
v > 4

array([False, False, False,  True, False,  True,  True,  True, False])

In [15]:
#Indexacion usando tipos buleanos
v[v > 4]

array([5., 5., 6., 7.])

In [16]:
print(v.shape) #atributo shape del arreglo de numpy (Formato de la matrix)
print(v.dtype) #atributo dtype (Tipos de datos que conforman el arreglo)
print(v.size) #atributo size (cantidad de elementos)
print(v.ndim) #atributo ndim (Dimensiones del arreglo)

(9,)
float64
9
1


## 2D arrays

```
# Tiene formato de código
```



Como se menciono antes, es posible crear arreglos de mayor dimension. en este caso , veamos los arreglos 2D (tambien conocidos como matrices)

In [4]:
#creacion de un arreglo 2D (matriz) usando una lista de python
entradas = [
            [2,6,4,8,9],
            [2,6,7,9,2.3],
            [5,6,3.,4,2.,],
            [9,0,5,3,6,],
            [3.6,2.7,9.8,2,4]
            ]

In [17]:
#creacion de un arreglo 2D (matriz) usando una lista de python
M = np.array(entradas)
M

array([[2. , 6. , 4. , 8. , 9. ],
       [2. , 6. , 7. , 9. , 2.3],
       [5. , 6. , 3. , 4. , 2. ],
       [9. , 0. , 5. , 3. , 6. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [22]:
#Indexacion en arreglos matriciales
M[0,0] , M[2,-1] , M[4,4]

(np.float64(2.0), np.float64(6.0), np.float64(4.0))

In [29]:
#Slicing en arreglos matriciales
# Filas: desde 0 hasta 5, paso 2 | Columna:  0 hasta la 4
M[0:6:2, 0:3]

array([[2. , 6. , 4. , 8. ],
       [5. , 6. , 3. , 4. ],
       [3.6, 2.7, 9.8, 2. ]])

In [20]:
#Slicing en arreglos matriciales
# # Filas: 0→6 paso 2 | Columnas: 0→6 paso 2
M[0:6:2, 0:6:2]

array([[2. , 4. , 9. ],
       [5. , 3. , 2. ],
       [3.6, 9.8, 4. ]])

In [30]:
#Slicing en arreglos matriciales
# Filas: 0→6 paso 2 | Columnas: TODAS
M[0:6:2, :]

array([[2. , 6. , 4. , 8. , 9. ],
       [5. , 6. , 3. , 4. , 2. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [31]:
#Slicing en arreglos matriciales
# Filas: TODAS | Columnas: Ultima
M[0:, -1]


array([9. , 2.3, 2. , 6. , 4. ])

In [40]:
#Slicing en arreglos matriciales
#Filas Todas | columas todas con paso 3
M[:, 0:-1:3]

array([[6. , 8. ],
       [6. , 9. ],
       [6. , 4. ],
       [0. , 3. ],
       [2.7, 2. ]])

In [41]:
#Otras formas de indexing usando listas de python
M[:,[0,2,4]]

array([[2. , 4. , 9. ],
       [2. , 7. , 2.3],
       [5. , 3. , 2. ],
       [9. , 5. , 6. ],
       [3.6, 9.8, 4. ]])

In [45]:
#Otras formas de indexing (termino a termino)
index = [[2,2],[0,0]], [[2,2],[0,0]]
M[index]

array([[3. , 5. ],
       [3.6, 2. ]])

In [46]:
#Indexacion usando tipos buleanos
M > 5

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False, False]])

In [48]:
#Indexacion usando tipos buleanos
M[M > 5]

array([6. , 8. , 9. , 6. , 7. , 9. , 6. , 9. , 6. , 9.8])

In [49]:
print(M.shape) #atributo shape del arreglo de numpy
print(M.dtype) #atributo dtype
print(M.size) #atributo size
print(M.ndim) #atributo ndim

(5, 5)
float64
25
2


Numpy tiene muchas funciones para crear arreglos

In [52]:
# Creación de un array de zeros
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [54]:
# Creación de un array de unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# Creación de un array de una costante
np.full(5 , 3)

array([3, 3, 3, 3, 3])

In [ ]:
np.full((3,3,3), 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [59]:
# Creación de la matriz indentidad de 2x2.
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Crea un vector desde el número inicial 4 hasta el final 10 de 0,2 en 0,2
np.arange(4,10,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [ ]:
# Crea un vector de diez valores espaciados la función encuentra el paso
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [ ]:
# Creación de un arreglo de valores aleatorios dados por una distribucion
#uniforme en el rango (0,1)
np.random.random(10)

array([0.73623658, 0.51370272, 0.07941719, 0.12944331, 0.03192888,
       0.34506528, 0.08902141, 0.08268152, 0.43762398, 0.77135962])

In [ ]:
np.random.random((2,2))

array([[0.26079813, 0.82823923],
       [0.06448793, 0.06129111]])

In [ ]:
# Creación arreglo de valores aleatorios dados por una distribucion normal
#loc: Media de la distribución (μ) - default: 0.0
#scale: Desviación estándar (σ) - default: 1.0
#size: Forma del array de salida (int o tupla) - default: None

np.random.normal(loc=5, scale=1, size=10)

array([5.54730031, 5.72995806, 4.24132714, 4.44741354, 3.61776274,
       4.38833216, 4.43500895, 5.37255682, 5.27866381, 4.48210496])

In [ ]:
np.random.normal(loc=0, scale=1, size=(3,3))

array([[-1.31358478,  1.00590217, -1.14564481],
       [ 0.24920212,  0.23690745, -0.51320557],
       [-0.64837712, -1.16955595,  1.02789509]])

In [ ]:
# Creación de una arreglo de números enteros aleatorios dados por una distribucion uniforme en el rango dado
np.random.randint(low = 2, high=10, size=10)

array([2, 5, 8, 5, 8, 2, 3, 4, 4, 9])

In [ ]:
np.random.randint(low = 2, high=10, size=(4,4))

array([[5, 7, 4, 8],
       [8, 6, 9, 7],
       [3, 4, 5, 5],
       [6, 5, 2, 8]])

## Ejercicios

\1) Crea una matriz de 3 x 3 con todos los valores true

In [63]:
Matriz=np.full((3,3),True)
Matriz

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2) Reemplace todos los numeros impares por -1
```
Input

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


In [65]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3) Convertir un array de 1D en uno de 2D con dos filas con la misma cantidad de elementos



```
Input:

arr = np.arange(16)
```

ayuda: Investigar el metodo `reshape ` que tienen los arreglos de numpy


In [76]:
arr = np.arange(16).reshape(2,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [71]:
help(np.hstack)

Help on _ArrayFunctionDispatcher in module numpy:

hstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence horizontally (column wise).

    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.

    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.24

    c

4) Convierte los vectores fila a y b en un vector columna (Apila verticalmente los vectores a y b)

```
Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

ayuda: investigar las funciones np.vstack , np.hstack

In [106]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

Vc = np.vstack(a.T)
Vc1 = np.vstack(b.T)
print(Vc)
print(Vc1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [103]:
a.reshape(1,-1,)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [102]:
ab=np.hstack((a,b))
ab

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

5) Identifica los elementos iguales en a y b



```
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

ayuda: investigar la funcion np.where


In [109]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

indices = np.where(a == b)
print("Elementos iguales:", a[indices])

Elementos iguales: [2 2 4 4]


6) Intercambiar las columnas 1 y 2 en el array arr

arr = np.arange(9).reshape(3,3)




```
arr = np.arange(9).reshape(3,3)
```



In [116]:
arr = np.arange(9).reshape(3,3)
arr[:, [0, 1]] = arr[:, [1, 0]]

print(arr)


[[1 0 2]
 [4 3 5]
 [7 6 8]]


## Operaciones basicas entre entre arreglos del mismo tamaño

Las operaciones basicas entre arreglos se dan elemento a elemnto

In [118]:
#definamos los dos arreglos
v = np.random.randint(low = 2, high=10, size=10)
w = np.random.randint(low = 2, high=10, size=10)
v,w

(array([4, 3, 7, 8, 5, 7, 8, 8, 8, 3]), array([6, 9, 6, 3, 9, 8, 2, 7, 3, 9]))

In [119]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v , w - v

(array([10, 12, 13, 11, 14, 15, 10, 15, 11, 12]),
 array([ 2,  6, -1, -5,  4,  1, -6, -1, -5,  6]))

In [120]:
#multiplicacion y division
w*v , w/v

(array([24, 27, 42, 24, 45, 56, 16, 56, 24, 27]),
 array([1.5       , 3.        , 0.85714286, 0.375     , 1.8       ,
        1.14285714, 0.25      , 0.875     , 0.375     , 3.        ]))

In [121]:
#Potenciacion
w**v

array([   1296,     729,  279936,    6561,   59049, 2097152,     256,
       5764801,    6561,     729])

In [122]:
#definamos los dos arreglos 2D
v = np.random.randint(low = 2, high=10, size=(3,3))
w = np.random.randint(low = 2, high=10, size=(3,3))
v,w

(array([[3, 2, 8],
        [8, 7, 6],
        [2, 7, 5]]),
 array([[8, 6, 2],
        [6, 8, 5],
        [4, 2, 8]]))

In [123]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v

array([[11,  8, 10],
       [14, 15, 11],
       [ 6,  9, 13]])

In [124]:
#multiplicacion y division
w*v

array([[24, 12, 16],
       [48, 56, 30],
       [ 8, 14, 40]])

In [125]:
#Potenciacion
w**v

array([[    512,      36,     256],
       [1679616, 2097152,   15625],
       [     16,     128,   32768]])

## Operaciones basicas entre entre arreglos de diferente tamaño (Broadcasting)

In [126]:
#definamos un arreglo 1D con numeros aleatorios
v = np.random.randint(low = 2, high=10, size=10)

In [127]:
#suma y resta de un arreglo y una constante
v, v + 1 , v - 1

(array([6, 3, 2, 6, 5, 9, 8, 2, 6, 4]),
 array([ 7,  4,  3,  7,  6, 10,  9,  3,  7,  5]),
 array([5, 2, 1, 5, 4, 8, 7, 1, 5, 3]))

In [128]:
#multiplicacion  y division de un arreglo y una constante
v*2 , v/2

(array([12,  6,  4, 12, 10, 18, 16,  4, 12,  8]),
 array([3. , 1.5, 1. , 3. , 2.5, 4.5, 4. , 1. , 3. , 2. ]))

In [129]:
#Comparaciones entre arreglo y una constante
v > 5

array([ True, False, False,  True, False,  True,  True, False,  True,
       False])

In [130]:
#Definamos dos arreglos con diferentes damaños
v = np.random.randint(low = 2, high=10, size=(4,4))
w = np.random.randint(low = 2, high=10, size=(1,4))
v , w

(array([[7, 7, 9, 2],
        [4, 4, 4, 2],
        [8, 6, 9, 6],
        [8, 3, 7, 4]]),
 array([[4, 8, 5, 7]]))

In [131]:
#Suma entre los dos arreglos
w + v

array([[11, 15, 14,  9],
       [ 8, 12,  9,  9],
       [12, 14, 14, 13],
       [12, 11, 12, 11]])

In [132]:
#Multiplicacion
w*v

array([[28, 56, 45, 14],
       [16, 32, 20, 14],
       [32, 48, 45, 42],
       [32, 24, 35, 28]])

In [133]:
#exponenciacion
w**v

array([[  16384, 2097152, 1953125,      49],
       [    256,    4096,     625,      49],
       [  65536,  262144, 1953125,  117649],
       [  65536,     512,   78125,    2401]])

## Ufunctions

algunos ejemplso de Ufunctions


In [134]:
#definamos dos arreglos 1D con numeros aleatorios
v = np.random.random(11)
v

array([0.9341626 , 0.5508211 , 0.40531293, 0.53291219, 0.30670666,
       0.3401152 , 0.09970323, 0.38285632, 0.42715849, 0.02588922,
       0.01273968])

In [135]:
v

array([0.9341626 , 0.5508211 , 0.40531293, 0.53291219, 0.30670666,
       0.3401152 , 0.09970323, 0.38285632, 0.42715849, 0.02588922,
       0.01273968])

In [136]:
#sumar las componenetes de un arreglo
np.sum(v)

np.float64(4.018377613853127)

In [137]:
#funciones trigonometricas
np.sin(v)

array([0.80410153, 0.52338706, 0.39430636, 0.50804385, 0.30192063,
       0.33359569, 0.09953812, 0.37357152, 0.41428629, 0.02588633,
       0.01273934])

In [138]:
#exponencial
np.exp(v)

array([2.5450813 , 1.73467677, 1.49977175, 1.70388713, 1.35894228,
       1.40510945, 1.10484298, 1.46646732, 1.53289559, 1.02622726,
       1.01282118])

In [139]:
#multiplicacion
np.multiply(v,v)

array([8.72659754e-01, 3.03403882e-01, 1.64278571e-01, 2.83995402e-01,
       9.40689762e-02, 1.15678348e-01, 9.94073359e-03, 1.46578965e-01,
       1.82464377e-01, 6.70251669e-04, 1.62299437e-04])

In [140]:
#media
np.mean(v)

np.float64(0.3653070558048297)

In [141]:
#desviacion estandar
np.std(v)

np.float64(0.2533341064510281)

## Ejercicios

Para los siguientes ejercicios concidere el suguiente conjunto de datos

In [142]:
#librearia que contiene el conjunto de tados llamados iris
from sklearn.datasets import load_iris

# **Conjunto de datos Iris**

Este conjunto de datos consta de 3 tipos diferentes de iris: (Setosa, Versicolor y Virginica) pétalo y sépalo length, almacenado en una matriz numpy.ndarray de 150x4

Las filas son las muestras y las columnas son: Longitud del sépalo, ancho del sépalo, longitud del pétalo y ancho del pétalo.

El siguiente gráfico utiliza las dos primeras características. Ver aquí para más información sobre este conjunto de datos.

In [143]:
#utilizamos la funcion load_iris() para cargar los datos
dataset = load_iris()

In [144]:
#Inspecciones un poco los datos , tenga encuenta que los datos vienen en forma de diccionario
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [145]:
#veamos la descripcion del data set
dataset['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [146]:
#veamos el nombre de las caracteristicas
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [147]:
#veamos las etiquetas
dataset['filename']

'iris.csv'

In [148]:
#separemos los datos
X = dataset['data'][: , [0,1]]

In [149]:
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

1) Obtenga el valor maximo y el valor minimo de la matriz X, luego obtenga el valor maximo y minimo de cada una de las columnas (esto es cada una de las caracteristicas)

In [163]:
Ma= np.max(X)
Mi= np.min(X)

print("El máximo es:", Ma)
print("El mínimo es:", Mi)

Ma_col = np.max(X, axis=0)
Mi_col = np.min(X, axis=0)

print("Máximos por columna:", Ma_col)
print("Mínimos por columna:", Mi_col)


El máximo es: 7.9
El mínimo es: 2.0
Máximos por columna: [7.9 4.4]
Mínimos por columna: [4.3 2. ]


2) Obtenga el valor medio, la mediana y la desviacion estandar para cada una de las caracteristicas
['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [177]:
features = dataset['feature_names']


media = np.mean(X, axis=0)
mediana = np.median(X, axis=0)
desviacion = np.std(X, axis=0)


for i, feature in enumerate(features):
    print(f"{feature}:")
    print(f"  Media = {media[i]:.3f}")
    print(f"  Mediana = {mediana[i]:.3f}")
    print(f"  Desviación estándar = {desviacion[i]:.3f}\n")

sepal length (cm):
  Media = 5.843
  Mediana = 5.800
  Desviación estándar = 0.825

sepal width (cm):
  Media = 3.057
  Mediana = 3.000
  Desviación estándar = 0.434

petal length (cm):
  Media = 3.758
  Mediana = 4.350
  Desviación estándar = 1.759

petal width (cm):
  Media = 1.199
  Mediana = 1.300
  Desviación estándar = 0.760



3) Para cada una de las caracteristicas identifique:
- la cantidad de valores mayores a las medias
- Extraiga los cuartiles de una de las variables (Recuerde que los cuartiles se calculan con los datos ordenados)

In [179]:
medias = np.mean(X, axis=0)

mayores_a_media = np.sum(X > medias, axis=0)

for i, feature in enumerate(features):
    print(f"{feature}:")
    print(f"  Media = {medias[i]:.3f}")
    print(f"  Cantidad de valores mayores a la media = {mayores_a_media[i]}")
    print()

sepal_length = X[:, 0]

q1 = np.percentile(sepal_length, 25)
q2 = np.percentile(sepal_length, 50)
q3 = np.percentile(sepal_length, 75)

print("Cuartiles de 'sepal length (cm)':")
print(f"  Q1 (25%) = {q1:.3f}")
print(f"  Q2 (50%) = {q2:.3f}")
print(f"  Q3 (75%) = {q3:.3f}")

sepal length (cm):
  Media = 5.843
  Cantidad de valores mayores a la media = 70

sepal width (cm):
  Media = 3.057
  Cantidad de valores mayores a la media = 67

petal length (cm):
  Media = 3.758
  Cantidad de valores mayores a la media = 93

petal width (cm):
  Media = 1.199
  Cantidad de valores mayores a la media = 90

Cuartiles de 'sepal length (cm)':
  Q1 (25%) = 5.100
  Q2 (50%) = 5.800
  Q3 (75%) = 6.400


# Bibliografia

- [Documentación Numpy](https://numpy.org/devdocs/index.html)